# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"


[server]
end-point-concurrency = 8
grpc-concurrency = 2
labels = {  }

[storage]

[pd]
# This section will be overwritten by command line parameters

[metric]
address = "172.16.30.10:9091"
interval = "15s"
job = "tikv"

[raftstore]
raftdb-path = ""
sync-log = false

[coprocessor]

[rocksdb]
wal-dir = ""

[rocksdb.defaultcf]
block-cache-size = "12GB"

[rocksdb.lockcf]

[rocksdb.writecf]
block-cache-size = "5GB"

[raftdb]

[raftdb.defaultcf]
block-cache-size = "2GB"

[security]
